### ISSUE TITLE
mongoHandler.js creates multikey compound indexes if you have > 1 Joi.many(...) defined per resource.

### ISSUE THREAD

**Issue by jbockerstette** [holidayextras/jsonapi-store-mongodb#32] opened 2016-06-21 17:08 UTC
This flaw essentially makes it impossible to have more than one Joi.many () in a single resource. As soon as you try to add elements to both arrays, it will fail. The fix is to just create an index for each array. Here is my fix. I tried to submit a PR but there is another change that I don't think you want. Anyways, here is my fix. If you just say collection.createIndex(index), it creates the bogus multikey compound index. Here is my commit to my fork.

https://github.com/jbockerstette/jsonapi-store-mongodb/commit/c05dbbf4c73ec0fbd5973d8a1e5738621a25d838

```
MongoStore.prototype._createIndexesForRelationships = function(collection, relationshipAttributeNames) {
  if (!Array.isArray(relationshipAttributeNames) || !relationshipAttributeNames.length) return;

  var index = relationshipAttributeNames.reduce(function(partialIndex, name) {
    if (name) {
      partialIndex[name + ".id"] = 1;
    }
    return partialIndex;
  }, {});
  if (Object.keys(index).length) {
    for (var nextIndex in index)
    {
      collection.createIndex(nextIndex);
    }
  }
};

```

**Comment by pmcnr-hx** [comment] 2016-06-21 21:17
Thanks for reporting this @jbockerstette. I couldn't reproduce your issue, but you are right in that we want individual indexes for each related resource. #33 should fix it if you want to give it a test (we should be merging it soon).

**Comment by pmcnr-hx** [comment] 2016-06-25 19:34
Closing since #33 has been merged and published to [npm](https://www.npmjs.com/package/jsonapi-store-mongodb).

**Closed by pmcnr-hx** 2016-06-25 19:34 UTC
